name: buudi_partner_app
description: Application externe Buudi Africa pour les Chauffeurs et Livreurs (courses, gains, statut, suivi GPS).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  buudi_shared:
    path: ../buudi_shared

  flutter_bloc: ^8.1.5
  http: ^1.2.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  firebase_core: ^2.31.0
  firebase_messaging: ^14.7.20
  firebase_database: ^10.5.7
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.6
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/branding/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/branding/app_icon_foreground_1024.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  # Force un fond blanc et centre/réduit l'aigle pour qu'il ne déborde pas des bords.
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/branding/app_icon_foreground_1024.png"
